alias bup="brew update; brew upgrade `brew outdated`; brew cleanup"
alias e="emacs -nw"
alias ec="emacsclient -t -a nano"
alias irc="irssi"
alias irssi="TERM=screen-256color irssi"
alias ls="ls -la"
alias red="pgrep -i emacs | xargs kill; emacs --daemon > /dev/null 2>&1;"
alias ta="tmux attach"
alias tm="tmux new-session -s"
alias zup="upgrade_oh_my_zsh"
alias gbgc="git branch | grep -v "master" | xargs git branch -D"