alias e="emacs -nw"
alias ec="emacsclient -t -a nano"
alias gbgc="git branch | grep -v "master" | xargs git branch -D"
alias gpg="gpg2"
alias irc="irssi"
alias irssi="TERM=screen-256color irssi"
alias ls="ls -la"
alias ta="tmux attach"
alias tm="tmux new-session -s"
alias zup="upgrade_oh_my_zsh"