#!/usr/bin/env bash

set -ex

# install rails
gem install rails

# restart psql
pg_ctl -D /usr/local/var/postgres restart

# create template in tmp directory
TMPFILE=$(mktemp /tmp/rails-new-api.XXXX)
cat << EOF > $TMPFILE
run "rm Gemfile"
file "Gemfile", <<-RUBY
source "https://rubygems.org"

ruby "#{RUBY_VERSION}"

gem "rails", "~> 6.0.2"

gem "bootsnap", ">= 1.4.2", require: false
gem "pg", ">= 0.18", "< 2.0"
gem "puma", "~> 4.1"
gem "rack-cors"

group :development, :test do
  gem "fabrication"
  gem "pry-rails"
  gem "rspec-rails"
end

group :development do
  gem "annotate"
  gem "listen", ">= 3.0.5", "< 3.2"
end

group :test do
  gem "airborne"
  gem "shoulda-matchers"
end
RUBY

after_bundle do
  run "rails generate annotate:install"
  run "rails generate rspec:install"
  append_to_file "spec/rails_helper.rb" do
    <<~CFG

    # Shoulda Matchers provides RSpec one-liners to test common Rails functionality
    Shoulda::Matchers.configure do |config|
      config.integrate do |with|
        with.test_framework :rspec
        with.library :rails
      end
    end
    CFG
  end

  git :init
  git add: "."
  git commit: %Q{ -m 'initial commit' }
end
EOF

# create new rails app
rails new $1 --api --database=postgresql --skip-spring -T --template=$TMPFILE

# clean up
rm "$TMPFILE"
